### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by br-zezowski** [JorgenPhi/cloudflare2db#1]
Is it possible to use this with Windows?

**Comment by JorgenPhi** [comment]
Yes. You will need to install PHP and run it from the command prompt.

**Comment by br-zezowski** [comment]
Thanks for your attention.

I'm getting this error: 

> PS C:\Users\victo\Desktop\influxdb-1.4.2-1> php scrape.php
> Cloudflare Stats -> Database v1.0
> ========================================
> PHP Notice:  Undefined property: stdClass::$influxhost in C:\Users\victo\Desktop\influxdb-1.4.2-1\scrape.php on line 29
> 
> Notice: Undefined property: stdClass::$influxhost in C:\Users\victo\Desktop\influxdb-1.4.2-1\scrape.php on line 29
> PHP Notice:  Undefined property: stdClass::$influxport in C:\Users\victo\Desktop\influxdb-1.4.2-1\scrape.php on line 29
> 
> Notice: Undefined property: stdClass::$influxport in C:\Users\victo\Desktop\influxdb-1.4.2-1\scrape.php on line 29
> Processing estrategiaconcursos.com.br

What does it mean? How should I configure that config.json file?

**Comment by JorgenPhi** [comment]
My sample config did not update with the rest of the app, just fixed that. Try setting it up again using the new config file.

**Comment by br-zezowski** [comment]
Thanks, Jorgen! It's working now, the scrape.php file, etc... 

But why won't my InfluxDB receive any data from Cloudflare? May you help me with this?
